# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
#tasks:
#  - name: Script Task 1
#    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#    command: echo 'start script'

#image:
#    file: .gitpod.Dockerfile

tasks:
    - before: sdk install java 17.0.4.1-tem